apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config
data:
  {{- $files := .Files }}
  {{- range tuple "SqlCmdScript.sql" }}
  {{ . }}: |-
    {{ $files.Get . }} 
  {{- end }}