apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  {{- $files := .Files }}
  {{- range tuple "SqlCmdScript.sql" }}
  {{ . | quote }}: |-
    {{ $files.Get . | nindent 5 }} 
  {{- end }}