apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACCEPT_EULA
              value: "{{ .Values.env.ACCEPT_EULA }}"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: saPassword
          volumeMounts:
            - name: sql-script
              mountPath: /SqlCmdScript.sql
              subPath: SqlCmdScript.sql
      volumes:
        - name: sql-script
          configMap:
            name: {{ .Release.Name }}-mysql-config
