apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.managementPort }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "{{ .Values.auth.username }}"
            - name: RABBITMQ_DEFAULT_PASS
              value: "{{ .Values.auth.password }}"
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
