image:
  repository: 
  name: jobs_api
  tag: latest
  

service:
  type: ClusterIP
  protocol: TCP
  port: 8083

env:
  CONNECTION_STRING: "Server=sql-data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs"
  HostRabbitmq: "rabbitmq"

resources:
  limits:
    cpu: "1"
    memory: "1500Mi"
  requests:
    cpu: "0.5"
    memory: "500Mi"
