image:
  repository: projetcloudobsm2
  name: jobs_api
  tag: latest
  

service:
  type: LoadBalancer
  protocol: TCP
  port: 80

env:
  ConnectionString: "Server=sql-data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs"
  HostRabbitmq: "rabbitmq"

resources:
  limits:
    cpu: "1"
    memory: "1500Mi"
  requests:
    cpu: "0.5"
    memory: "500Mi"
