apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #cert-manager.io/issuer: "letsencrypt-prod"

  name: redirect-front-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - *.cloudobsm2.com
    secretName: my-tls-secret
  rules:
  - host : cloudobsm2.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: web #TODO: Change this to the name of the service when we have it
            port: 
              number: 80

  