apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCrt | b64enc | quote }}
  tls.key: {{ .Values.tlsKey | b64enc | quote }}