image:
  repository: rabbitmq
  tag: 3-management
  pullPolicy: IfNotPresent

service:
  protocol: TCP
  type: ClusterIP
  port: 5672
  managementPort: 15672

auth:
  username: guest
  password: guest

persistence:
  enabled: false 

resources:
  limits:
    cpu: "1"
    memory: "1500Mi"
  requests:
    cpu: "0.5"
    memory: "500Mi"
