image:
  repository: fluent/fluentd-kubernetes-daemonset
  tag: v1.18-debian-elasticsearch8-1
  pullPolicy: IfNotPresent

elasticsearch:
  host: "elasticsearch.default.svc.cluster.local"
  port: 9200

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

persistence:
  enabled: false
