replicaCount: 1
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.5.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9200

environment:
  - name: discovery.type
    value: single-node
  - name: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - name: xpack.security.enabled
    value: "false"
  
persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi