apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host {{ .Values.elasticsearch.host }}
      port {{ .Values.elasticsearch.port }}
      logstash_format true
      logstash_prefix kubernetes-logs
      flush_interval 5s
      type_name _doc
      include_type_name false
    </match>

    <filter kubernetes.**>
      @type parser
      key_name time
      reserve_time true
      reserve_data true
        <parse>
          @type json
          time_key timestamp
          time_format %Y-%m-%dT%H:%M:%S.%LZ
        </parse>
      </filter>
      
    <filter kubernetes.**>
      @type record_modifier
      <record>
        @timestamp ${time.strftime('%Y-%m-%dT%H:%M:%S.%LZ')}
      </record>
    </filter>

