apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.pos
      tag kubernetes.*
      format json
      time_key time
      time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <match kubernetes.**>
      @type elasticsearch
      host {{ .Values.elasticsearch.host }}
      port {{ .Values.elasticsearch.port }}
      logstash_format true
      logstash_prefix fluentd
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      flush_interval 5s
    </match>

    <filter kubernetes.**>
      @type parser
      key_name log
      format json
      time_key time
      reserve_data true
    </filter>
      

