apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      initContainers:
        - name: fix-log-permissions
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /var/log/containers /var/lib/docker/containers"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
        - name: copy-fluentd-config
          image: busybox
          command: ["/bin/sh", "-c", "cp /fluentd-config/fluent.conf /fluentd/etc/fluent.conf && chmod 644 /fluentd/etc/fluent.conf"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd-config
            - name: fluentd-config
              mountPath: /fluentd/etc/
      containers:
        - name: fluentd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc/
            - name: varlog
              mountPath: /var/log
              readOnly: false
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: fluentd-config
          emptyDir: {}
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
