image:
  repository: projetcloudobsm2
  name: identity_api
  tag: latest

service:
  type: ClusterIP
  protocol: TCP
  port: 8084

env:
  RedisHost: "user-data:6379"
  HostRabbitmq: "rabbitmq"

resources:
  limits:
    cpu: "1"
    memory: "1500Mi"
  requests:
    cpu: "0.5"
    memory: "500Mi"
